version: '3.8'

services:
  backend:
    build: .
    container_name: hpc_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis_broker:6379/0
      - MONGO_URI=mongodb://mongo_db:27017
      - MONGO_DB_NAME=hpc_cluster_db
      - SERVER_IP=192.168.1.8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - redis_broker
      - mongo_db
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  redis_broker:
    image: redis:alpine
    container_name: hpc_redis

  mongo_db:
    image: mongo:latest
    container_name: hpc_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: